export const ALERT_FETCH_ALERTS = "alert/FETCH_ALERTS";
export const ALERT_FETCH_ALERTS_SUCCESS = "alert/FETCH_ALERTS_SUCCESS";
export const ALERT_FETCH_ALERTS_ERROR = "alert/FETCH_ALERTS_ERROR";
export const ALERT_IS_FETCHING_ALERTS = "alert/IS_FETCHING_ALERTS";
export const ALERT_SORT_BY_ALERTS = "alert/SORT_BY_ALERTS";
export const ALERT_CHANGE_PAGE = "alert/CHANGE_PAGE";
export const ALERT_CHANGE_PAGE_SIZE = "alert/CHANGE_PAGE_SIZE";
export const ALERT_RECEIVE_NEW_ALERT = "alert/RECEIVE_NEW_ALERT";
export const ALERT_SELECT_ALERT = "alert/SELECT_ALERT";


// TODO refractor rest ...
export const LOADING_ALERTS_START = "LOADING_ALERTS_START";
export const LOADING_ALERTS_END = "LOADING_ALERTS_END";

export const GET_INITIAL_ALERTS_SUCCESS = "GET_INITIAL_ALERTS_SUCCESS";
export const GET_INITIAL_ALERTS_ERROR = "GET_INITIAL_ALERTS_ERROR";

export const GET_FILTERED_ALERTS = "GET_FILTERED_ALERTS";
export const GET_FILTERED_ALERTS_SUCCESS = "GET_FILTERED_ALERTS_SUCCESS";
export const GET_FILTERED_ALERTS_ERROR = "GET_FILTERED_ALERTS_ERROR";

export const UPDATE_ALERTS = "UPDATE_ALERTS";

export const ADD_ALERTS_FILTER = "ADD_ALERTS_FILTER";
export const UPDATE_ALERTS_FILTER = "UPDATE_ALERTS_FILTER";
export const REMOVE_ALERTS_FILTER = "REMOVE_ALERTS_FILTER";
export const CLEAR_ALERTS_FILTERS = "CLEAR_ALERTS_FILTERS";
export const FETCH_FILTERED_ALERTS = "FETCH_FILTERED_ALERTS";
export const FETCH_FILTERED_ALERTS_SUCCESS = "FETCH_FILTERED_ALERTS_SUCCESS";
export const FETCH_FILTERED_ALERTS_ERROR = "FETCH_FILTERED_ALERTS_ERROR";
export const SET_SELECTED_ALERT = "SET_SELECTED_ALERT";
export const SET_PAGE = "SET_PAGE";
export const SET_ROWS_PER_PAGE = "SET_ROWS_PER_PAGE";
export const SET_PAGING_INFO = "SET_PAGING_INFO";
export const SET_ARE_FILTERED = "SET_ARE_FILTERED";


export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const UPDATE_SNACKBAR = "UDPATE_SNACKBAR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const UPDATE_MODAL_CONTENT = "UPDATE_MODAL_CONTENT";
export const CHANGE_MODAL_TAB = "CHANGE_MODAL_TAB";


